# Generated by Django 2.2.6 on 2019-10-19 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('solo', models.CharField(max_length=255)),
                ('swapi_apearece', models.IntegerField(default=0)),
            ],
        ),
    ]
