# Generated by Django 2.2.6 on 2019-10-24 13:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='swapi_apearece',
        ),
        migrations.AddField(
            model_name='planet',
            name='films',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
